### ISSUE TITLE
Keeper v0.6 to v0.7 plan

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#297]
# Keeper v0.7 Plan

## Ocean Token

- [ ] Document the requirements and high level architecture (28/Jan)
- [ ] Document the keeper tasks to accomplish (28/Jan)

### Requirements

It's necessary to document the agreements made in the meeting (Bruce, Trent, Don, Dimi, Chalid, etc)

Notes:

- Ocean Token must live in Ethereum mainnet and Pacific POA. It means should be deployed independentlly of other keeper contracts. So we have 2 options (ask Sebastian):
  - Separate the Ocean Token in a different repos
  - Implement an additional migration script deploying only the Ocean Token 

- During the migration phase: 
  - All the unvested balance is migrated immediatly
  - The vested balance is migrated to the OPF pending further distribution. We are not having vesting business logic on-chain
  - This is going to be controlled by an external software releasing the tokens when the vesting period is over (out of keeper contracts) (Chalid)
- Different responsibilities will be assigned to different roles in the system. Each role will have the capability to interact with keeper contracts:
  - Contract Deployer/Owner: Can deploy contracts. In the keeper-contracts is managed using ZeppelinOS with MultiSig
  - Contract Upgrader: Can upgrade contracts. In the keeper-contracts is managed using ZeppelinOS with MultiSig
  - Genesis Role: Have control over the Genesis Dispenser. Needs to be registered on-chain (TODO). Will have the ability to mint all the 520.7M tokens from the initial allocation. This is out of keeper contracts (Chalid). The Genesis Dispenser lives on-chain.
  - Rewards Role: Have the capabillities of distribute the rewards (889.3M) between different accounts of the system. Initially is not going to have any business logic.
  - Bridge Operator: In charge of mirroring or migrating the Ocean Tokens between Ethereum Mainnet and Pacific POA
  - Node Operator: Have the capability of managing the physical infrastructure. It means adding or removing nodes to the POA network, etc..
 

### Architecture

Architecture definition can be found here:
https://docs.google.com/presentation/d/14FmmLn4mCMptxAarbl04WmqRi6OuSB4Bv72Dd8wlp1Y/edit?usp=sharing

### Tasks

Define the tasks using as input the requirements & architecture

- [ ] Formalize the specs of the Ocean Token
- [ ] Validate if current interface of the Token is aligned
- [ ] Setup the workflow. Converting the specs to tests in plain English
- [ ] Formalize the tests in the keeper contracts project using the current testing framework
- [ ] Implementation of the pending Ocean Token business logic
- [ ] Unit & End to End tests
- [ ] Separate Ocean Token from the existing contracts deployment
- [ ] Validate everything works okay with ZeppelinOS
- [ ] Deploy the Ocean Token into Nile and run Acceptance Test

#### OceanToken.sol

When this tasks are done we should have an ERC20 token with a cap and correct Owner and Minter roles. Tasks:

- [ ] Setup the correct amount of the cap: 1.41 10E9
- [ ] Choose the right ticker (not OCN)
- [ ] Setup the initial Minter. Validation!!. Separate the Deployer from the Minter. Currently the user who is deploying the contract is the Minter registered in the system
- [ ] Define the flow to add/renounce Minters is correct. This need need to be battle tested.

#### Dispenser.sol

- [ ] Create an abstraction of the Dispenser class
- [ ] Create the logic for setting up the MAX_MINT_AMOUNT. As well the validation of that.
- [ ] UT + E2E testing of the complete flow. We have to be able to register/renounce Dispenser and validate corner case scenarios. Taking into account we are going to need to add in the coming future additional Dispensers (NetworkRewardDispenser).

#### GenesisDispenser.sol

Once this tasks are done the GenesisDispenser should be able to handle the end to end genesis acquisition flow.

- [ ] Create a Smart contract extending the abstract Dispenser.sol
- [ ] Set the roles for deploying and transfering. Who is the one able to do that.
- [ ] Define the MAX_MINT_AMOUNT = 520.7M
- [ ] Define & Implement the capabilities of Minting and Transferring tokens to accounts
- [ ] UT + E2E Testing of the lifecycle of the Dispenser
- [ ] Testing in conjunction with MultiSigWallet
- [ ] Testing in using a batch script scenario (Manan) (Nile)

#### MultiSigWallet.sol

Once this is done we should be able to validate that MultiSigWallet only allows to the proper owners to operate in the system. Tasks:

- [ ] Validate the current contract
- [ ] Set the roles of the owners that are initialized
- [ ] Validate the way of adding/removing owners is the logic we want
- [ ] Set the threshold. The amount of signatures required. And validate the update of this value.
- [ ] Battle tested submit, confirm, revoke and executeTransaction methods
- [ ] E2E test in conjunction with the dispenser

#### Tasks

TokenBridge needs to be tested in all the scenarios. Main task is to understand how to operate the bridge in a live environment scenario. What happens if the complete network is down? How to recover the system? Are funds losts? How to distribute the agents?
Tasks:

- [ ] E2E flow meets the specs
- [ ] Validate if we need to add the Bridge role in the system
- [ ] Anaylisis about how to operate the bridge network
- [ ] Test the E2E flow including corner cases. What happens if all the validators are offline? 
- [ ] Understand how to apply MultiSigWallet for deployment
- [ ] Understand if we need to apply zeppelinOS to the Bridge contracts

## Service Execution Agreements (SEA)

- [x] Document the requirements and high level architecture (28/Jan)
- [ ] Document the keeper tasks to accomplish (28/Jan)

### Requirements

Mini-OEP's:
- https://github.com/oceanprotocol/OEPs/issues/125
- https://github.com/oceanprotocol/OEPs/issues/122
- https://github.com/oceanprotocol/OEPs/issues/121
- https://github.com/oceanprotocol/OEPs/issues/120
- https://github.com/oceanprotocol/OEPs/issues/119

### Architecture

Presentation and OEPs made by Dimi

### Tasks

- [ ] Formalize the specs of the SEA (review and approve)
- [ ] Validate the delta
- [ ] Setup the workflow. Converting the specs to tests in plain English
- [ ] Formalize the tests in the keeper contracts project using the current testing framework
- [ ] Implementation of the pending SEA business logic
- [ ] Unit & End to End tests
- [ ] Validate everything works okay with ZeppelinOS
- [ ] Deploy the keeper-contracts into Nile and run Acceptance Test

#### The fucking Delta (v0.6 -> v0.7)

- [ ] We need to implement the 3 storage contracts (AgreementStore, TemplateStore, ConditionStore)
- [ ] Review Access Control for storage functions
- [ ] Unify and validate the content based addressing (details in Dimi presentation)
- [ ] Review the attributes that need to be removed or renamed
- [ ] Move logic to the appropiate classes
- [ ] Review the existing modifiers
- [ ] Review the existing events. Make sure the indexed parameters are properly flagged
- [ ] Review if we can encapsulate common tools/functions in Helper classes
- [ ] E2E testing

## Execution Plan

It's necessary to formalize this plan in DevOcean.

- Define requirements
- Define architecture
- Define public interfaces
- Define tasks
- Define tests in plain english
- Formalize tests
- Start writting code
- Check tests
- E2E
