### ISSUE TITLE
Adaptation of extended Service Execution Agreements for Tethis v1.0

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#309]
### Requirements

Mini-OEP's:
- https://github.com/oceanprotocol/OEPs/issues/125
- https://github.com/oceanprotocol/OEPs/issues/122
- https://github.com/oceanprotocol/OEPs/issues/121
- https://github.com/oceanprotocol/OEPs/issues/120
- https://github.com/oceanprotocol/OEPs/issues/119

### Architecture

Presentation and Mini-OEPs made by Dimi

https://docs.google.com/presentation/d/1rDkkxuC-dWuPQ0bcseC0vzFsqYj70wx-SNFU4ZFQH70/edit?usp=sharing

### Tasks

- [ ] Formalize the specs of the SEA (review and approve) (https://github.com/oceanprotocol/ocean/issues/254)
- [ ] Validate the delta between keeper v0.6 and v0.7
- [ ] Setup the workflow. Converting the specs to tests in plain English
- [ ] Formalize the tests in the keeper contracts project using the current testing framework
- [ ] Implementation of the pending SEA business logic
- [ ] Unit & End to End tests
- [ ] Validate everything works okay with ZeppelinOS
- [ ] Deploy the keeper-contracts into Nile and run Acceptance Test

#### The fucking Delta (v0.6 -> v0.7)

- [ ] We need to implement the 3 storage contracts (AgreementStore, TemplateStore, ConditionStore)
- [ ] Review Access Control for storage functions
- [ ] Unify and validate the content based addressing (details in Dimi presentation)
- [ ] Review the attributes that need to be removed or renamed
- [ ] Move logic to the appropriate classes
- [ ] Review the existing modifiers
- [ ] Review the existing events. Make sure the indexed parameters are properly flagged
- [ ] Review if we can encapsulate common tools/functions in Helper classes
- [ ] E2E testing
