### ISSUE TITLE
Keeper technical dept

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#65]
The idea is to list the things to refactor in the Keeper side (sorted by priority):

- [x] Automate docker release #70
- [x] Automate NPM publish #71
- [x] Automate pypi release #72
- [ ] Discuss/change ABI/Address handling #73
- [ ] Create, human readable, documentation from solidity smart contracts #74
- [x] remove ./build folder from npm package #60  
- [x] Keeper-contracts need proper unit tests #78
- [ ] ...

After reviewing this, each entry will be an independent user story to be implemented in the following days.

Implements: https://github.com/oceanprotocol/ocean/issues/96

**Comment by H34D** [comment]
closed in favour of https://github.com/oceanprotocol/ocean/issues/234
